name: Compile

on: [push]

jobs:
  build-ubuntu:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: configure
        run:  sudo apt install libasound2-dev libsndfile1-dev libdbus-1-dev && mkdir build && cd build && cmake ..
      - name: build
        run: cd build && make -j2 && make check
